/**
 * NOTE: This class is auto generated by the swagger code generator program ().
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.ibm.stock.controller;

import com.ibm.stock.model.Stock;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;
import javax.validation.Valid;
@javax.annotation.Generated(value = "com.ibm.mobile.sdkgen.platform.JavaSpringBootCodegenConfig", date = "2017-10-21T21:39:11.308Z")

@Api(value = "stock", description = "The Stock API")
public interface StockItemsApi {

    @ApiOperation(value = "", notes = "Add new stock item", response = Stock.class, tags={ "stock", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "One Stock Item", response = Stock.class) })
    @RequestMapping(value = "/stock",
        produces = { "application/json" }, 
        consumes = { "text/plain" },
        method = RequestMethod.POST)
    ResponseEntity<Stock> add(@ApiParam(value = "Product name", required = true) @Valid @RequestBody String productName, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;


    @ApiOperation(value = "", notes = "Get all Stock Items", response = Stock.class, responseContainer = "List", tags={ "stock", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "List of all Stock Items", response = Stock.class, responseContainer = "array") })
    @RequestMapping(value = "/stock/items",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Stock>> getAll(@RequestHeader(value = "Accept", required = false) String accept) throws Exception;

}
