/**
 * NOTE: This class is auto generated by the swagger code generator program ().
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.ibm.stock.service;

import com.ibm.stock.model.Product;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
@javax.annotation.Generated(value = "com.ibm.mobile.sdkgen.platform.JavaSpringBootCodegenConfig", date = "2017-10-21T21:39:11.308Z")

@Api(value = "product", description = "the product API")
public interface ProductApi {

    @ApiOperation(value = "", notes = "Delete product by ID", response = Product.class, tags={ "products", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "One product", response = Product.class) })
    @RequestMapping(value = "/product/{id}",
        produces = { "application/json" }, 
        consumes = { "text/plain" },
        method = RequestMethod.DELETE)
    ResponseEntity<Product> delete(@ApiParam(value = "Product ID", required = true) @PathVariable("id") Long id, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;


    @ApiOperation(value = "", notes = "Get product by ID", response = Product.class, tags={ "products", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "One product", response = Product.class) })
    @RequestMapping(value = "/product/{id}",
        produces = { "application/json" }, 
        consumes = { "text/plain" },
        method = RequestMethod.GET)
    ResponseEntity<Product> get(@ApiParam(value = "Product ID", required = true) @PathVariable("id") Long id, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;


    @ApiOperation(value = "", notes = "Update product by ID", response = Product.class, tags={ "products", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "One product", response = Product.class) })
    @RequestMapping(value = "/product/{id}",
        produces = { "application/json" }, 
        consumes = { "text/plain" },
        method = RequestMethod.PUT)
    ResponseEntity<Product> update(@ApiParam(value = "Product ID", required = true) @PathVariable("id") Long id, @ApiParam(value = "Product name", required = true) @Valid @RequestBody String productName, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;

}
